---

- hosts: all
  become: true
  tasks:
  - name: update repositories for Ubuntu
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
     
  - name: install apache2 and php  for Ubuntu
    apt: 
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: update repositories for CentOS
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install apache and php for CentOS
    dnf: 
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"
    